name:                LCCI
version:             0.1.0.0
github:              "rmellema/LCCI"
license:             BSD3
author:              "René Mellema"
maintainer:          "rene.mellema@gmail.com"
copyright:           "Copyright: (c) 2018 René Mellema"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Package used for evaluating statements in LCCI models, used for my Master Thesis
category:            Logic

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/rmellema/LCCI#readme>

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src

tests:
  LCCI-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LCCI
